title: M19O Blog
iconURL: assets/1.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter:
  github: M19O

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 2291
google_analytics: UA-NNNNNNNN-N
